import React, { useState } from 'react';
import { useCRM } from '../context/CRMContext';
import { 
  Sparkles, TrendingUp, AlertTriangle, CheckCircle2, 
  ArrowRight, ShieldCheck, Plus, Mail, Calendar, DollarSign,
  UserCheck, Building2, Flame, Layers
} from 'lucide-react';

interface AIInsightsPageProps {
  onNavigate: (tab: string) => void;
}

export const AIInsightsPage: React.FC<AIInsightsPageProps> = ({ onNavigate }) => {
  const { aiInsights, createTask, leads, deals, companies } = useCRM();
  const [activeCategory, setActiveCategory] = useState<'all' | 'nba' | 'leads' | 'deals' | 'churn'>('all');
  const [executingActionId, setExecutingActionId] = useState<string | null>(null);

  const handleExecuteAction = async (action: any) => {
    setExecutingActionId(action.id);
    try {
      await createTask({
        title: action.payload?.title || `AI Recommendation: ${action.company_name}`,
        customer_name: action.company_name,
        priority: 'Urgent',
        due_date: new Date(Date.now() + 86400000).toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).replace(/ /g, ' '),
        assigned_to: 'Amit Sharma',
        description: `Action item generated by AI Intelligence: ${action.recommended_action}`,
        is_ai_generated: true
      });
      alert(`Action executed! Task "${action.payload?.title || action.recommended_action}" added to queue.`);
    } catch (err) {
      console.error(err);
    } finally {
      setExecutingActionId(null);
    }
  };

  const nextBestActions = aiInsights?.next_best_actions || [
    {
      id: 'nba-1',
      company_name: 'TechNova Solutions',
      context: 'Executive proposal under active review (12 opens detected).',
      recommended_action: 'Schedule a product demonstration & closing call within 24 hours.',
      rationale: 'High executive engagement + pricing review + decision maker Rahul Sharma active.',
      action_label: 'Create Closing Task',
      payload: { title: 'Closing meeting with TechNova Sales Director', customer_name: 'TechNova Solutions' }
    },
    {
      id: 'nba-2',
      company_name: 'FinEdge Systems',
      context: 'Pricing objection detected regarding annual prepayment terms.',
      recommended_action: 'Offer customized annual-plan pricing with complimentary onboarding instead of discounting base price.',
      rationale: 'Protects gross margin while satisfying VP of Operations budget parameters.',
      action_label: 'Generate ROI Proposal',
      payload: { title: 'Draft ROI Proposal for FinEdge', customer_name: 'FinEdge Systems' }
    },
    {
      id: 'nba-3',
      company_name: 'Global Solutions Ltd',
      context: 'Customer health dropped to 42/100; zero telemetry logged in 28 days.',
      recommended_action: 'Initiate executive sponsor retention intervention.',
      rationale: '81% churn probability unless immediate customer success check-in is conducted.',
      action_label: 'Schedule Retention Check-in',
      payload: { title: 'Customer Retention Review - Global Solutions', customer_name: 'Global Solutions Ltd' }
    }
  ];

  const leadScoring = aiInsights?.lead_scoring || leads.map(l => ({
    id: l.id,
    lead_name: `${l.first_name} ${l.last_name}`,
    company: l.company,
    score: l.lead_score,
    probability: l.lead_score >= 80 ? 'High probability' : 'Medium probability',
    reasons: l.ai_reasons || ["Recent activity", "Budget matched"],
    recommended_action: l.ai_recommended_action || "Schedule follow-up call",
    value: `₹${l.lead_value.toLocaleString()}`
  }));

  const dealPredictions = aiInsights?.deal_predictions || deals.map(d => ({
    id: d.id,
    deal_name: d.deal_name,
    company_name: d.company_name,
    deal_value_formatted: `₹${(d.deal_value/100000).toFixed(1)} L`,
    win_probability: d.probability,
    expected_revenue: `₹${(d.deal_value * d.probability / 10000000).toFixed(2)} L`,
    risk_factor: d.risk_factor,
    ai_recommendation: d.ai_recommendation,
    owner: d.owner
  }));

  const churnPredictions = aiInsights?.churn_predictions || companies.map(c => ({
    id: c.id,
    company_name: c.name,
    city: c.city,
    churn_risk: c.churn_risk,
    churn_probability: c.churn_probability,
    health_score: c.customer_health,
    reasons: [
      c.churn_risk === 'High' ? 'Support complaint unresolved' : 'Regular platform engagement',
      'Contract renewal approaching'
    ],
    recommendation: c.ai_recommendation || 'Conduct quarterly review'
  }));

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px' }}>
      {/* Header */}
      <div>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div style={{
            width: '32px',
            height: '32px',
            borderRadius: '8px',
            backgroundColor: '#7C3AED',
            display: 'flex',
            alignItems: 'center',
            justifyContent: 'center',
            color: '#FFFFFF'
          }}>
            <Sparkles size={18} />
          </div>
          <h1 style={{ fontSize: '24px', fontWeight: 800, letterSpacing: '-0.02em' }}>
            AI Business Intelligence & Predictive Analytics
          </h1>
        </div>
        <p style={{ fontSize: '13.5px', color: 'var(--text-secondary)', marginTop: '4px' }}>
          Explainable machine learning predictions for Lead Conversion, Deal Win Probability, Churn Prevention, and Next-Best-Action guidance.
        </p>
      </div>

      {/* Category Pills */}
      <div style={{ display: 'flex', gap: '10px', flexWrap: 'wrap' }}>
        {[
          { id: 'all', label: 'All Intelligence' },
          { id: 'nba', label: `Next Best Actions (${nextBestActions.length})` },
          { id: 'leads', label: `Lead Scoring (${leadScoring.length})` },
          { id: 'deals', label: `Deal Forecasts (${dealPredictions.length})` },
          { id: 'churn', label: `Churn & Health (${churnPredictions.length})` }
        ].map(tab => (
          <button
            key={tab.id}
            onClick={() => setActiveCategory(tab.id as any)}
            className={`btn btn-sm ${activeCategory === tab.id ? 'btn-primary' : 'btn-secondary'}`}
          >
            {tab.label}
          </button>
        ))}
      </div>

      {/* SECTION: NEXT BEST ACTIONS */}
      {(activeCategory === 'all' || activeCategory === 'nba') && (
        <div className="card" style={{ padding: '20px 24px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '16px' }}>
            <Flame size={18} color="var(--accent-amber)" />
            <h2 style={{ fontSize: '17px', fontWeight: 800 }}>Prioritized Next Best Actions</h2>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '16px' }}>
            {nextBestActions.map((nba: any) => (
              <div
                key={nba.id}
                style={{
                  padding: '16px 18px',
                  borderRadius: '12px',
                  backgroundColor: 'var(--bg-muted)',
                  border: '1px solid var(--border-color)',
                  display: 'flex',
                  flexDirection: 'column',
                  justifyContent: 'space-between',
                  gap: '12px'
                }}
              >
                <div>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <span style={{ fontSize: '14.5px', fontWeight: 800 }}>{nba.company_name}</span>
                    <span className="badge badge-accent">AI Priority</span>
                  </div>
                  <p style={{ fontSize: '12.5px', color: 'var(--text-secondary)', marginTop: '4px' }}>
                    <strong>Signal:</strong> {nba.context}
                  </p>
                  <p style={{ fontSize: '13px', marginTop: '8px', color: 'var(--text-primary)', lineHeight: 1.4 }}>
                    <strong>Action:</strong> {nba.recommended_action}
                  </p>
                  <p style={{ fontSize: '11.5px', color: 'var(--text-muted)', marginTop: '4px' }}>
                    <em>Rationale: {nba.rationale}</em>
                  </p>
                </div>

                <div style={{ display: 'flex', justifyContent: 'flex-end', marginTop: '6px' }}>
                  <button
                    onClick={() => handleExecuteAction(nba)}
                    disabled={executingActionId === nba.id}
                    className="btn btn-primary btn-sm"
                  >
                    {executingActionId === nba.id ? 'Creating Task...' : nba.action_label}
                  </button>
                </div>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* SECTION: LEAD SCORING */}
      {(activeCategory === 'all' || activeCategory === 'leads') && (
        <div className="card" style={{ padding: '20px 24px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <Sparkles size={18} color="var(--accent-blue)" />
              <h2 style={{ fontSize: '17px', fontWeight: 800 }}>Lead Scoring & Conversion Probability</h2>
            </div>
            <button onClick={() => onNavigate('leads')} className="btn btn-ghost btn-sm">
              Open Leads Module <ArrowRight size={13} />
            </button>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '14px' }}>
            {leadScoring.map((l: any) => (
              <div key={l.id} className="card" style={{ padding: '16px', display: 'flex', flexDirection: 'column', gap: '10px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div>
                    <h4 style={{ fontSize: '14.5px', fontWeight: 700 }}>{l.lead_name}</h4>
                    <span style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>{l.company}</span>
                  </div>
                  <div style={{
                    width: '38px',
                    height: '38px',
                    borderRadius: 'var(--radius-full)',
                    background: l.score >= 80 ? 'rgba(5, 150, 105, 0.12)' : 'rgba(217, 119, 6, 0.12)',
                    color: l.score >= 80 ? 'var(--accent-emerald)' : 'var(--accent-amber)',
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'center',
                    fontWeight: 800,
                    fontSize: '13px'
                  }}>
                    {l.score}
                  </div>
                </div>

                <div style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
                  <strong>Opportunity:</strong> {l.value} • <span style={{ color: 'var(--accent-blue)' }}>{l.probability}</span>
                </div>

                <p style={{ fontSize: '12.5px', color: 'var(--text-primary)', background: 'var(--bg-muted)', padding: '8px', borderRadius: '6px' }}>
                  💡 {l.recommended_action}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}

      {/* SECTION: DEAL PREDICTIONS */}
      {(activeCategory === 'all' || activeCategory === 'deals') && (
        <div className="card" style={{ padding: '20px 24px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <TrendingUp size={18} color="var(--accent-emerald)" />
              <h2 style={{ fontSize: '17px', fontWeight: 800 }}>Deal Win Probability & Risk Radar</h2>
            </div>
            <button onClick={() => onNavigate('deals')} className="btn btn-ghost btn-sm">
              Open Deals Module <ArrowRight size={13} />
            </button>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '14px' }}>
            {dealPredictions.map((d: any) => (
              <div key={d.id} className="card" style={{ padding: '16px', display: 'flex', flexDirection: 'column', gap: '10px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' }}>
                  <div>
                    <h4 style={{ fontSize: '14.5px', fontWeight: 700 }}>{d.deal_name}</h4>
                    <span style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>{d.company_name}</span>
                  </div>
                  <span style={{ fontSize: '13px', fontWeight: 800, color: d.win_probability >= 70 ? 'var(--accent-emerald)' : 'var(--accent-amber)' }}>
                    {d.win_probability}% Win Prob
                  </span>
                </div>

                <div style={{ fontSize: '12.5px', color: 'var(--text-secondary)' }}>
                  Value: <strong>{d.deal_value_formatted}</strong> • Weighted Forecast: <strong>{d.expected_revenue}</strong>
                </div>

                {d.risk_factor && (
                  <div style={{ fontSize: '12px', color: 'var(--accent-rose)', background: 'rgba(225, 29, 72, 0.08)', padding: '6px 8px', borderRadius: '6px' }}>
                    ⚠️ {d.risk_factor}
                  </div>
                )}
              </div>
            ))}
          </div>
        </div>
      )}

      {/* SECTION: CHURN & RETENTION */}
      {(activeCategory === 'all' || activeCategory === 'churn') && (
        <div className="card" style={{ padding: '20px 24px' }}>
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '16px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '8px' }}>
              <AlertTriangle size={18} color="var(--accent-rose)" />
              <h2 style={{ fontSize: '17px', fontWeight: 800 }}>Account Health & Predictive Churn Alerts</h2>
            </div>
            <button onClick={() => onNavigate('companies')} className="btn btn-ghost btn-sm">
              Open Companies Module <ArrowRight size={13} />
            </button>
          </div>

          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: '14px' }}>
            {churnPredictions.map((c: any) => (
              <div key={c.id} className="card" style={{ padding: '16px', display: 'flex', flexDirection: 'column', gap: '10px' }}>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                  <div>
                    <h4 style={{ fontSize: '14.5px', fontWeight: 700 }}>{c.company_name}</h4>
                    <span style={{ fontSize: '12px', color: 'var(--text-muted)' }}>{c.city}</span>
                  </div>
                  <span className={`badge ${c.churn_risk === 'High' ? 'badge-urgent' : c.churn_risk === 'Medium' ? 'badge-normal' : 'badge-low'}`}>
                    {c.churn_risk} Churn Risk
                  </span>
                </div>

                <div style={{ display: 'flex', justifyContent: 'space-between', fontSize: '12.5px' }}>
                  <span>Customer Health:</span>
                  <strong>{c.health_score}/100</strong>
                </div>

                <p style={{ fontSize: '12px', color: 'var(--text-secondary)' }}>
                  💡 {c.recommendation}
                </p>
              </div>
            ))}
          </div>
        </div>
      )}
    </div>
  );
};
